SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

INSERT INTO `sitChamp` (`idChamp`, `idChampParent`, `libelle`, `stockage`, `xpath`, `scope`, `versioning`, `plugin`, `bordereau`, `liste`, `identifiant`, `cle`) VALUES
(3, NULL, 'Contact Etablissement - Raison sociale', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:RaisonSociale', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'raison_sociale', 'N'),
(5, NULL, 'Informations légales - Siret', 'xml', 'tif:InformationsLegales/tif:SIRET', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'siret', 'N'),
(9, NULL, 'Informations légales - APE / NAF', 'xml', 'tif:InformationsLegales/tif:APE_NAF', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'ape_naf', 'N'),
(36, NULL, 'Type d''établissement', 'xml', 'tif:DublinCore/tif:ControlledVocabulary', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'type_etablissement', 'N'),
(40, NULL, 'Contact Etablissement - Adresse 1', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Adr1', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'adresse1', 'N'),
(41, NULL, 'Contact Etablissement - Adresse 2', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Adr2', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'adresse2', 'N'),
(42, NULL, 'Contact Etablissement - Adresse 3', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse/tif:Adr3', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'adresse3', 'N'),
(43, NULL, 'Contact Etablissement - Code postal', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:CodePostal', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'code_postal', 'N'),
(44, NULL, 'Contact Etablissement - Cedex', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse/tif:Cedex', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'cedex', 'N'),
(45, NULL, 'Contact Etablissement - Commune', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Commune[1]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'commune', 'N'),
(46, NULL, 'Contact Etablissement - Pays', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse/tif:Pays', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', 'LS_Pays', 'pays', 'N'),
(47, NULL, 'Contact Etablissement - Téléphone 1', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][1]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'telephone1', 'N'),
(48, NULL, 'Contact Etablissement - Téléphone 2', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][2]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'telephone2', 'N'),
(49, NULL, 'Contact Etablissement - Fax', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.02"]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'fax', 'N'),
(50, NULL, 'Contact Etablissement - Site web', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.05"][1]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'site_web', 'N'),
(51, NULL, 'Contact Etablissement - Email', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.04"][1]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'email', 'N'),
(52, NULL, 'Informations légales - RCS', 'xml', 'tif:InformationsLegales/tif:RCS', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'rcs', 'N'),
(53, NULL, 'Description commerciale FR', 'xml', 'tif:DublinCore/dc:description[attribute::xml:lang="fr"][1]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'description_commerciale_fr', 'N'),
(54, NULL, 'Description commerciale EN', 'xml', 'tif:DublinCore/dc:description[attribute::xml:lang="en"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'description_commerciale_en', 'N'),
(55, NULL, 'Description commerciale DE', 'xml', 'tif:DublinCore/dc:description[attribute::xml:lang="de"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'description_commerciale_de', 'N'),
(56, NULL, 'Description commerciale ES', 'xml', 'tif:DublinCore/dc:description[attribute::xml:lang="es"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'description_commerciale_es', 'N'),
(57, NULL, 'Description commerciale NL', 'xml', 'tif:DublinCore/dc:description[attribute::xml:lang="nl"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'description_commerciale_nl', 'N'),
(58, NULL, 'Description commerciale IT', 'xml', 'tif:DublinCore/dc:description[attribute::xml:lang="it"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'description_commerciale_it', 'N'),
(59, NULL, 'Slogan FR', 'xml', 'tif:DescriptionsComplementaires/tif:DetailDescriptionComplementaire[attribute::type="16.01.04"]/tif:Description[attribute::type="16.02.01" and attribute::xml:lang="fr"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'slogan_fr', 'N'),
(60, NULL, 'Slogan EN', 'xml', 'tif:DescriptionsComplementaires/tif:DetailDescriptionComplementaire[attribute::type="16.01.04"]/tif:Description[attribute::type="16.02.01" and attribute::xml:lang="en"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'slogan_en', 'N'),
(61, NULL, 'Slogan DE', 'xml', 'tif:DescriptionsComplementaires/tif:DetailDescriptionComplementaire[attribute::type="16.01.04"]/tif:Description[attribute::type="16.02.01" and attribute::xml:lang="de"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'slogan_de', 'N'),
(62, NULL, 'Slogan ES', 'xml', 'tif:DescriptionsComplementaires/tif:DetailDescriptionComplementaire[attribute::type="16.01.04"]/tif:Description[attribute::type="16.02.01" and attribute::xml:lang="es"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'slogan_es', 'N'),
(63, NULL, 'Slogan NL', 'xml', 'tif:DescriptionsComplementaires/tif:DetailDescriptionComplementaire[attribute::type="16.01.04"]/tif:Description[attribute::type="16.02.01" and attribute::xml:lang="nl"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'slogan_nl', 'N'),
(64, NULL, 'Slogan IT', 'xml', 'tif:DescriptionsComplementaires/tif:DetailDescriptionComplementaire[attribute::type="16.01.04"]/tif:Description[attribute::type="16.02.01" and attribute::xml:lang="it"]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'slogan_it', 'N'),
(65, NULL, 'Langues parlées - Accueil', 'xml', 'tif:Langues/tif:Usage[attribute::type="11.01.01"]/tif:Langue', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'langues_parlees_accueil', 'N'),
(66, NULL, 'Capacités Globales - Nombre de chambres', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.02"][1]/tif:Capacite[attribute::unite="01.03.01.03" and attribute::classee="O"][1]', NULL, NULL, NULL, 'HOT,HLO', '', 'capacite_chambre', 'N'),
(67, NULL, 'Capacités Globales - Nombre de personnes', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.07"]/tif:Capacite[attribute::unite="01.03.01.09" and attribute::classee="O"]', NULL, NULL, NULL, 'HOT,ORG,PRD', '', 'capacite_personne', 'N'),
(68, NULL, 'Capacités Globales - Nombre de salles de réunion', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.02.24"]/tif:Capacite[attribute::unite="01.03.01.13" and attribute::classee="O"]', NULL, NULL, NULL, 'HOT', '', 'capacite_salle', 'N'),
(69, NULL, 'Capacités Globales - Superficie (m2)', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.03"]/tif:Superficie[attribute::unite="01.03.04.01" and attribute::classee="N"]', NULL, NULL, NULL, 'HOT', '', 'capacite_superficie', 'N'),
(70, NULL, 'Classements - Classement préfectoral', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.04.01"][1]/tif:Classement[1]/@type', NULL, NULL, NULL, 'HOT,HPA,HLO,VIL,ORG', 'LS_Classement', 'classement', 'N'),
(71, NULL, 'Classements - Date du classement', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.04.01"]/tif:DateClassement', NULL, NULL, NULL, 'HOT,HPA,HLO,VIL,ORG', '', 'date_classement', 'N'),
(72, NULL, 'Classements - Numéro du classement', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.04.01"]/tif:NumeroClassement', NULL, NULL, NULL, 'HOT,HPA,HLO,VIL,ORG', '', 'numero_classement', 'N'),
(73, NULL, 'Contacts', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'contact', 'N'),
(74, 73, 'Type de contact', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Contact', 'type_contact', 'Y'),
(75, 73, 'Raison sociale', 'xml', 'tif:RaisonSociale', NULL, NULL, NULL, NULL, '', 'raison_sociale', 'N'),
(76, 73, 'Civilité', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Civilite/@type', NULL, NULL, NULL, NULL, 'LS_Civilite', 'civilite', 'N'),
(77, 73, 'Prénom', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Prenom', NULL, NULL, NULL, NULL, '', 'prenom', 'N'),
(78, 73, 'Nom', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Nom', NULL, NULL, NULL, NULL, '', 'nom', 'N'),
(79, 73, 'Fonction', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Fonction', NULL, NULL, NULL, NULL, '', 'fonction', 'N'),
(80, 73, 'Adresse 1', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Adr1', NULL, NULL, NULL, NULL, '', 'adresse1', 'N'),
(81, 73, 'Adresse 2', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Adr2', NULL, NULL, NULL, NULL, '', 'adresse2', 'N'),
(82, 73, 'Adresse 3', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Adr3', NULL, NULL, NULL, NULL, '', 'adresse3', 'N'),
(83, 73, 'Code postal', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:CodePostal', NULL, NULL, NULL, NULL, '', 'code_postal', 'N'),
(84, 73, 'Cedex', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Cedex', NULL, NULL, NULL, NULL, '', 'cedex', 'N'),
(85, 73, 'Code Insee', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Commune/@code', NULL, NULL, NULL, NULL, '', 'code_insee', 'N'),
(86, 73, 'Pays', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Pays/@code', NULL, NULL, NULL, NULL, 'LS_Pays', 'pays', 'N'),
(87, 73, 'Téléphone 1', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][1]/tif:Coord', NULL, NULL, NULL, NULL, '', 'telephone1', 'N'),
(88, 73, 'Téléphone 2', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][2]/tif:Coord', NULL, NULL, NULL, NULL, '', 'telephone2', 'N'),
(89, 73, 'Fax', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.02"]/tif:Coord', NULL, NULL, NULL, NULL, '', 'fax', 'N'),
(90, 73, 'Site web', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.05"][1]/tif:Coord', NULL, NULL, NULL, NULL, '', 'site_web', 'N'),
(91, 73, 'Email', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.04"]/tif:Coord', NULL, NULL, NULL, NULL, '', 'email', 'N'),
(92, NULL, 'Géolocalisation - Environnement', 'xml', 'tif:Geolocalisations/tif:DetailGeolocalisation[attribute::type="08.01.02"]/tif:Zone[attribute::type="08.02.07.02"]/tif:Points/tif:DetailPoint[attribute::type="08.02.05.11"]/tif:Environnements/tif:DetailEnvironnement', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'environnement', 'N'),
(93, 92, 'Type d''environnement', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Environnement', 'type', 'Y'),
(94, 92, 'Nom', 'xml', 'tif:Nom', NULL, NULL, NULL, NULL, '', 'nom', 'N'),
(95, 92, 'Distance', 'xml', 'tif:Distance', NULL, NULL, NULL, NULL, '', 'distance', 'N'),
(96, 92, 'Unité ', 'xml', 'tif:Distance/@unite', NULL, NULL, NULL, NULL, 'LS_DistanceUnite', 'unite_distance', 'N'),
(97, NULL, 'Géolocalisation - Points d''accès', 'xml', 'tif:Geolocalisations/tif:DetailGeolocalisation[attribute::type="08.01.02"]/tif:Zone[attribute::type="08.02.07.02"]/tif:Points/tif:DetailPoint[attribute::type="08.02.05.11"]/tif:Acces/tif:DetailAcces', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'points_acces', 'N'),
(98, 97, 'Type d''accès', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Acces', 'type', 'Y'),
(99, 97, 'Nom', 'xml', 'tif:Nom', NULL, NULL, NULL, NULL, '', 'nom', 'N'),
(100, 97, 'Distance', 'xml', 'tif:Distance', NULL, NULL, NULL, NULL, '', 'distance', 'N'),
(101, 97, 'Unité', 'xml', 'tif:Distance/@unite', NULL, NULL, NULL, NULL, 'LS_DistanceUnite', 'unite_distance', 'N'),
(102, NULL, 'Géolocalisation - Latitude', 'xml', 'tif:Geolocalisations/tif:DetailGeolocalisation[attribute::type="08.01.02"]/tif:Zone[attribute::type="08.02.07.02"]/tif:Points/tif:DetailPoint[attribute::type="08.02.05.11"][1]/tif:Coordonnees/tif:DetailCoordonnees[attribute::type="08.02.02.03"]/tif:Latitude', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'gps_lat', 'N'),
(103, NULL, 'Géolocalisation - Longitude', 'xml', 'tif:Geolocalisations/tif:DetailGeolocalisation[attribute::type="08.01.02"]/tif:Zone[attribute::type="08.02.07.02"]/tif:Points/tif:DetailPoint[attribute::type="08.02.05.11"][1]/tif:Coordonnees/tif:DetailCoordonnees[attribute::type="08.02.02.03"]/tif:Longitude', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'gps_lng', 'N'),
(104, NULL, 'Prestations - Equipements', 'xml', 'tif:OffresPrestations/tif:DetailOffrePrestation[attribute::type="15.05"]/tif:DetailPrestation', NULL, NULL, NULL, 'HOT,HPA,HLO,PCU,PNA,RES,DEG,LOI,ASC,VIL', 'LS_Prestation', 'equipement', 'N'),
(105, NULL, 'Prestations - Conforts', 'xml', 'tif:OffresPrestations/tif:DetailOffrePrestation[attribute::type="15.03"]/tif:DetailPrestation', NULL, NULL, NULL, 'HOT,HPA,HLO,RES,DEG,ASC,VIL', 'LS_Prestation', 'confort', 'N'),
(106, NULL, 'Prestations - Services', 'xml', 'tif:OffresPrestations/tif:DetailOffrePrestation[attribute::type="15.06"]/tif:DetailPrestation', NULL, NULL, NULL, 'HOT,HPA,HLO,PCU,PNA,RES,DEG,LOI,ASC,VIL', 'LS_Prestation', 'service', 'N'),
(107, NULL, 'Tarifs', 'xml', 'tif:Tarifs/tif:DetailTarifs/tif:DetailTarif', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,PRD', '', 'tarif', 'N'),
(108, 107, 'Type de tarifs', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Tarifs', 'type_tarif', 'Y'),
(109, 107, 'Nom', 'xml', 'tif:Nom', NULL, NULL, NULL, NULL, '', 'nom', 'N'),
(110, 107, 'Tarif unique', 'xml', 'tif:TarifStandard', NULL, NULL, NULL, NULL, '', 'tarifstandard', 'N'),
(111, 107, 'Tarif min', 'xml', 'tif:TarifMin', NULL, NULL, NULL, NULL, '', 'tarifmin', 'N'),
(112, 107, 'Tarif max', 'xml', 'tif:TarifMax', NULL, NULL, NULL, NULL, '', 'tarifmax', 'N'),
(113, 107, 'Date de début', 'xml', 'tif:DetailPeriode[attribute::type="09.01.08"]/tif:Dates/tif:DetailDates/tif:DateDebut', NULL, NULL, NULL, NULL, '', 'datedebut', 'N'),
(114, 107, 'Date de fin', 'xml', 'tif:DetailPeriode[attribute::type="09.01.08"]/tif:Dates/tif:DetailDates/tif:DateFin', NULL, NULL, NULL, NULL, '', 'datefin', 'N'),
(115, 107, 'Personnes min', 'xml', 'tif:DetailClient[attribute::type="10.02.02"]/tif:NbPersMin', NULL, NULL, NULL, NULL, '', 'personnesmin', 'N'),
(116, 107, 'Personnes max', 'xml', 'tif:DetailClient[attribute::type="10.02.02"]/tif:NbPersMax', NULL, NULL, NULL, NULL, '', 'personnesmax', 'N'),
(117, NULL, 'Prestations - Activités', 'xml', 'tif:OffresPrestations/tif:DetailOffrePrestation[attribute::type="15.02"]/tif:DetailPrestation', NULL, NULL, NULL, 'HOT,HPA,HLO,PCU,PNA,RES,DEG,LOI,ASC,VIL', 'LS_Prestation', 'activite', 'N'),
(118, NULL, 'Périodes - Périodes d''ouverture', 'xml', 'tif:Periodes/tif:DetailPeriode', NULL, NULL, NULL, 'HOT,HPA,HLO,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'ouverture', 'N'),
(119, 118, 'Type de période', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Periode', 'type', 'Y'),
(120, 118, 'Date de début', 'xml', 'tif:Dates/tif:DetailDates/tif:DateDebut', NULL, NULL, NULL, NULL, '', 'datedebut', 'N'),
(121, 118, 'Date de fin', 'xml', 'tif:Dates/tif:DetailDates/tif:DateFin', NULL, NULL, NULL, NULL, '', 'datefin', 'N'),
(122, 118, 'Description', 'xml', 'tif:ObservationDetailPeriode[attribute::xml:lang="fr"]', NULL, NULL, NULL, NULL, '', 'description', 'N'),
(123, NULL, 'Capacités Globales - Nombre d''emplacements', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.04"]/tif:Capacite[attribute::unite="01.03.01.05" and attribute::classee="O"][1]', NULL, NULL, NULL, 'HPA', '', 'capacite_emplacement', 'N'),
(124, NULL, 'Capacités Globales - Nombre de personnes (emplacement)', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.04"]/tif:Capacite[attribute::unite="01.03.01.09" and attribute::classee="O"]', NULL, NULL, NULL, 'HPA,LOI', '', 'capacite_personne', 'N'),
(125, NULL, 'Capacités Unités - Emplacements Loisir', 'xml', 'tif:Capacites/tif:CapacitesUnites/tif:DetailCapaciteUnite[attribute::type="14.03.02.15"]/tif:NbUnites', NULL, NULL, NULL, 'HPA', '', 'capacite_loisir', 'N'),
(126, NULL, 'Capacités Unités - Emplacements Tourisme', 'xml', 'tif:Capacites/tif:CapacitesUnites/tif:DetailCapaciteUnite[attribute::type="14.03.02.16"]/tif:NbUnites', NULL, NULL, NULL, 'HPA', '', 'capacite_tourisme', 'N'),
(130, NULL, 'Capacités Globales - Superficie (m2)', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.04"]/tif:Superficie[attribute::unite="01.03.04.01" and attribute::classee="N"]', NULL, NULL, NULL, 'HPA,LOI', '', 'capacite_superficie', 'N'),
(132, NULL, 'Type FMA - Evénements', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.03.02")]', NULL, NULL, NULL, 'FMA', '', 'fma_evenements', 'N'),
(133, NULL, 'Type FMA - Types', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.03.04")]', NULL, NULL, NULL, 'FMA', '', 'fma_types', 'N'),
(134, NULL, 'Type FMA - Catégories', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.03.01")]', NULL, NULL, NULL, 'FMA', '', 'fma_categories', 'N'),
(146, NULL, 'Type PCU - Catégories de musées', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.01")]', NULL, NULL, NULL, 'PCU', '', 'pcu_categories_musees', 'N'),
(147, NULL, 'Classements - Tourisme et handicap', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.05"]/tif:Classement', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,RES,DEG,LOI,ASC,VIL,ORG', 'LS_TypeClassement', 'handicap', 'N'),
(148, NULL, 'Type DEG - Produits', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.02.01")]', NULL, NULL, NULL, 'DEG', '', 'deg_produits', 'N'),
(149, NULL, 'Type RES - Catégories', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.13.01")]', NULL, NULL, NULL, 'RES', '', 'res_categories', 'N'),
(150, NULL, 'Type RES - Types de cuisine', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.13.03")]', NULL, NULL, NULL, 'RES', '', 'res_types_cuisine', 'N'),
(151, NULL, 'Capacités Globales - Nombre de couverts', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.07"]/tif:Capacite[attribute::unite="01.03.01.04" and attribute::classee="O"]', NULL, NULL, NULL, 'RES', '', 'capacite_couvert', 'N'),
(152, NULL, 'Capacités Globales - Nombre de salles', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.06"]/tif:Capacite[attribute::unite="01.03.01.13" and attribute::classee="O"]', NULL, NULL, NULL, 'RES,ORG', '', 'capacite_salle', 'N'),
(154, NULL, 'Capacités Globales - Superficie (m2)', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.06"]/tif:Superficie[attribute::unite="01.03.04.01" and attribute::classee="N"]', NULL, NULL, NULL, 'RES', '', 'capacite_superficie', 'N'),
(156, NULL, 'Capacités Unités', 'xml', 'tif:Capacites/tif:CapacitesUnites/tif:DetailCapaciteUnite', NULL, NULL, NULL, 'HLO,RES,VIL', '', 'capacite', 'N'),
(157, NULL, 'Classements - Agréments', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.01"]/tif:Classement', NULL, NULL, NULL, 'VIL', 'LS_TypeClassement', 'agrement', 'N'),
(172, 105, 'Confort', 'xml', 'tif:Prestation/@type', NULL, NULL, NULL, NULL, 'LS_Prestation', 'cle', 'Y'),
(173, 117, 'Activite', 'xml', 'tif:Prestation/@type', NULL, NULL, NULL, NULL, 'LS_Prestation', 'cle', 'Y'),
(174, 117, 'Distance', 'xml', 'tif:Distance', NULL, NULL, NULL, NULL, '', 'distance', 'N'),
(175, 117, 'Unite', 'xml', 'tif:Distance/@unite', NULL, NULL, NULL, NULL, 'LS_Unite', 'unite', 'N'),
(176, 104, 'Equipement', 'xml', 'tif:Prestation/@type', NULL, NULL, NULL, NULL, 'LS_Prestation', 'cle', 'Y'),
(177, 106, 'Service', 'xml', 'tif:Prestation/@type', NULL, NULL, NULL, NULL, 'LS_Prestation', 'cle', 'Y'),
(201, NULL, 'Photos / Fichiers', 'xml', '/tif:OI/tif:Multimedia/tif:DetailMultimedia', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'photos_fichiers', 'N'),
(202, 201, 'Url', 'xml', 'tif:URL', NULL, NULL, NULL, NULL, '', 'url_fichier', 'N'),
(203, 201, 'Nom', 'xml', 'tif:Nom', NULL, NULL, NULL, NULL, '', 'nom_fichier', 'N'),
(204, NULL, 'Contact Etablissement - Code Insee', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Commune[1]/@code', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'code_insee', 'N'),
(205, NULL, 'Classements - Labels', 'xml', 'tif:Classements/tif:DetailClassement[contains(attribute::type, "06.06")]', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'label', 'N'),
(206, NULL, 'Classements - Chaines', 'xml', 'tif:Classements/tif:DetailClassement[contains(attribute::type, "06.02") and not(contains(attribute::type, "06.06.02"))]', NULL, NULL, NULL, 'HOT,HPA,HLO,VIL', '', 'chaine', 'N'),
(207, NULL, 'Tarifs - Modes de paiement', 'xml', 'tif:Tarifs/tif:ModesPaiement/tif:ModePaiement', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,PRD', '', 'mode_paiement', 'N'),
(212, 201, 'Type', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Multimedia', 'type_fichier', 'Y'),
(214, 201, 'Largeur', 'xml', 'tif:Largeur', NULL, NULL, NULL, NULL, '', 'largeur_fichier', 'N'),
(215, 201, 'Hauteur', 'xml', 'tif:Hauteur', NULL, NULL, NULL, NULL, '', 'hauteur_fichier', 'N'),
(216, 201, 'Taille', 'xml', 'tif:TailleRessource', NULL, NULL, NULL, NULL, '', 'taille_fichier', 'N'),
(217, 147, 'Handicap', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Classement', 'cle', 'Y'),
(219, 207, 'Mode de paiement', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_ModePaiement', 'cle', 'Y'),
(220, 205, 'Label simple', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_TypeClassement', 'cle', 'Y'),
(221, 206, 'Chaine', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_TypeClassement', 'cle', 'Y'),
(222, 157, 'Agrément', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Classement', 'cle', 'Y'),
(231, NULL, 'Classements - Label HPA (Bienvenue à la Ferme)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.01.01"]/tif:Classement/@type', NULL, NULL, NULL, 'HPA', 'LS_Classement', 'bienvenue_a_la_ferme', 'N'),
(232, NULL, 'Classements - Label HOT (Logis de France)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.03.01"][1]/tif:Classement[1]/@type', NULL, NULL, NULL, 'HOT', 'LS_Classement', 'logis_de_france', 'N'),
(233, NULL, 'Classements - Label HPA (Camping Qualité France)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.01.02"]/tif:Classement/@type', NULL, NULL, NULL, 'HPA', 'LS_Classement', 'camping_qualite_france', 'N'),
(234, NULL, 'Classements - Label HPA (Gîtes de France)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.01.03"][1]/tif:Classement/@type', NULL, NULL, NULL, 'HPA', 'LS_Classement', 'gites_de_france', 'N'),
(235, NULL, 'Classements - Label HLO (Locations CléVacances)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.02.02"][1]/tif:Classement[1]/@type', NULL, NULL, NULL, 'HLO', 'LS_Classement', 'locations_clevacances', 'N'),
(236, NULL, 'Classements - Label RES (Tables et auberges de France)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.04.03"]/tif:Classement/@type', NULL, NULL, NULL, 'RES', 'LS_Classement', 'tables_et_auberges_de_france', 'N'),
(237, NULL, 'Classements - Label VIL (Loisirs de France)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.05.01"]/tif:Classement/@type', NULL, NULL, NULL, 'VIL', 'LS_Classement', 'loisirs_de_france', 'N'),
(245, NULL, 'Classements - Label HOT (Michelin)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.06.12"]/tif:Classement/@type', NULL, NULL, NULL, 'HOT,RES', 'Ls_Classement', 'michelin', 'N'),
(246, 73, 'Commune', 'xml', 'tif:Adresses/tif:DetailAdresse/tif:Commune', NULL, NULL, NULL, NULL, '', 'commune', 'N'),
(248, 65, 'Langue', 'xml', '@lang', NULL, NULL, NULL, NULL, 'LS_Langues', 'langue', 'Y'),
(249, NULL, 'Langues parlées - Documentation', 'xml', 'tif:Langues/tif:Usage[attribute::type="11.01.06"]/tif:Langue', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'langues_parlees_documentation', 'N'),
(250, 249, 'Langue', 'xml', '@lang', NULL, NULL, NULL, NULL, 'LS_Langues', 'langue', 'N'),
(251, NULL, 'Langues parlées - Panneau', 'xml', 'tif:Langues/tif:Usage[attribute::type="11.01.07"]/tif:Langue', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'langues_parlees_panneau', 'N'),
(252, 251, 'Langue', 'xml', '@lang', NULL, NULL, NULL, NULL, 'LS_Langues', 'langue', 'N'),
(253, NULL, 'Langues parlées - Visite', 'xml', 'tif:Langues/tif:Usage[attribute::type="11.01.09"]/tif:Langue', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'langues_parlees_visite', 'N'),
(254, 253, 'Langue', 'xml', '@lang', NULL, NULL, NULL, NULL, 'LS_Langues', 'langue', 'N'),
(255, NULL, 'Langues parlées - Réservation', 'xml', 'tif:Langues/tif:Usage[attribute::type="11.01.10"]/tif:Langue', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'langues_parlees_reservation', 'N'),
(257, 255, 'Langue', 'xml', '@lang', NULL, NULL, NULL, NULL, 'LS_Langues', 'langue', 'N'),
(258, NULL, 'Disponibilités', 'xml', 'tif:Plannings/tif:DetailPlanning[attribute::type="19.02.01"]', NULL, NULL, NULL, 'HOT,HPA,HLO,RES,VIL,ORG', 'LS_Planning', 'disponibilites', 'N'),
(259, 258, 'Date début', 'xml', 'tif:DetailPeriode[attribute::type="09.01.07"]/tif:Dates/tif:DetailDate/tif:DateDebut', NULL, NULL, NULL, NULL, '', 'datedebut', 'N'),
(260, 258, 'Disponibilité', 'xml', 'tif:DetailPeriode[attribute::type="09.01.07"]/tif:ObservationPlanning', NULL, NULL, NULL, NULL, '', 'disponibilite', 'N'),
(261, 133, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(262, 36, 'Type', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(263, 150, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(264, 132, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(265, 134, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(266, 149, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(267, NULL, 'Type RES - Types', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.13.02")]', NULL, NULL, NULL, 'RES', '', 'res_types', 'N'),
(268, 267, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(269, NULL, 'Type FMA - Thèmes', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.03.03")]', NULL, NULL, NULL, 'FMA', '', 'fma_themes', 'N'),
(270, 269, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(271, 146, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(272, NULL, 'Type PCU - Catégories des parcs et jardins', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.02")]', NULL, NULL, NULL, 'PCU', '', 'pcu_categories_parcs_jardins', 'N'),
(273, NULL, 'Type PCU - Catégories des sites et monuments historiques', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.03")]', NULL, NULL, NULL, 'PCU', '', 'pcu_categories_sites_monuments', 'N'),
(274, NULL, 'Type PCU - Equipements principaux', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.04")]', NULL, NULL, NULL, 'PCU', '', 'pcu_equipements', 'N'),
(275, NULL, 'Type PCU - Styles architecturaux des parcs et jardins', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.05")]', NULL, NULL, NULL, 'PCU', '', 'pcu_styles_parcs_jardins', 'N'),
(276, NULL, 'Type PCU - Styles architecturaux des sites et monuments historiques', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.06")]', NULL, NULL, NULL, 'PCU', '', 'pcu_styles_sites_monuments', 'N'),
(277, NULL, 'Type PCU - Thèmes des musées', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.07")]', NULL, NULL, NULL, 'PCU', '', 'pcu_themes_musees', 'N'),
(278, NULL, 'Type PCU - Thèmes des parcs et jardins', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.08")]', NULL, NULL, NULL, 'PCU', '', 'pcu_themes_parcs_jardins', 'N'),
(279, NULL, 'Type PCU - Thèmes des sites et monuments historiques', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.09")]', NULL, NULL, NULL, 'PCU', '', 'pcu_themes_sites_monuments', 'N'),
(280, NULL, 'Type PCU - Types des centres d''interprétation', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.11.10")]', NULL, NULL, NULL, 'PCU', '', 'pcu_types_centres_interpretation', 'N'),
(281, 272, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(282, 273, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(283, 274, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(284, 275, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(285, 276, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(286, 277, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(287, 278, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(288, 279, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(289, 280, 'Code', 'xml', '@code\n', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(290, NULL, 'Type ASC - Activités culturelles', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.01.01")]', NULL, NULL, NULL, 'ASC', '', 'asc_activites_culturelles', 'N'),
(291, NULL, 'Type ASC - Activités sportives', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.01.02")]', NULL, NULL, NULL, 'ASC', '', 'asc_activites_sportives', 'N'),
(292, NULL, 'Type ASC - Catégorie d''activités sportives', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.01.03")]', NULL, NULL, NULL, 'ASC', '', 'asc_categorie_activites_sportives', 'N'),
(293, NULL, 'Type ASC - Formules itinérantes', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.01.04")]', NULL, NULL, NULL, 'ASC', '', 'asc_formules_itinerantes', 'N'),
(294, 290, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(295, 291, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(296, 292, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(297, 293, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(298, NULL, 'Type DEG - Statut de l''exploitant', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.02.02")]', NULL, NULL, NULL, 'DEG', '', 'deg_statut_exploitant', 'N'),
(299, 148, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(300, 298, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(301, NULL, 'Type ORG - Organismes de tourisme institutionnels', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.10.01")]', NULL, NULL, NULL, 'ORG', '', 'org_organismes_tourisme_institutionnels', 'N'),
(302, NULL, 'Type ORG - Organismes réceptifs', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.10.02")]', NULL, NULL, NULL, 'ORG', '', 'org_organismes_receptifs', 'N'),
(303, NULL, 'Type ORG - Services d''informations touristiques privés', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.10.03")]', NULL, NULL, NULL, 'ORG', '', 'org_services_informations_touristiques_prives', 'N'),
(304, NULL, 'Type ORG - Types d''entreprise', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.10.04")]', NULL, NULL, NULL, 'ORG', '', 'org_types_entreprise', 'N'),
(305, NULL, 'Type ORG - Types de structures', 'xml', 'tif:DublinCore/tif:ControlledVocabulary[contains(attribute::code, "02.01.10.05")]', NULL, NULL, NULL, 'ORG', '', 'org_types_structures', 'N'),
(306, 301, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(307, 302, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(308, 303, 'Code', 'xml', '@code', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(309, 304, 'Code', 'xml', '@code\n', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(310, 305, 'Code', 'xml', '@code\n', NULL, NULL, NULL, NULL, 'LS_ControlledVocabulary', 'cle', 'Y'),
(311, 258, 'Date fin', 'xml', 'tif:DetailPeriode[attribute::type="09.01.07"]/tif:Dates/tif:DetailDate/tif:DateFin', NULL, NULL, NULL, NULL, '', 'datefin', 'N'),
(319, NULL, 'Périodes - Date de Début FMA', 'xml', 'tif:Periodes/tif:DetailPeriode[attribute::type="09.01.05"]/tif:Dates/tif:DetailDates/tif:DateDebut', NULL, NULL, NULL, 'FMA', '', 'debut_manifestation', 'N'),
(320, NULL, 'Périodes - Date de Fin FMA', 'xml', 'tif:Periodes/tif:DetailPeriode[attribute::type="09.01.05"]/tif:Dates/tif:DetailDates/tif:DateFin', NULL, NULL, NULL, 'FMA', '', 'fin_manifestation', 'N'),
(321, NULL, 'Date de validité', 'xml', 'tif:DublinCore/dcterms:valid', NULL, NULL, NULL, 'FMA', '', 'valid', 'N'),
(322, NULL, 'Date de publication', 'xml', 'tif:DublinCore/dcterms:issued', NULL, NULL, NULL, 'FMA', '', 'issued', 'N'),
(323, 156, 'Type', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Unite', 'type', 'Y'),
(324, 156, 'Bâtiment', 'xml', 'tif:TypeBatiment/@type', NULL, NULL, NULL, NULL, 'LS_TypeBatiment', 'batiment', 'N'),
(325, 156, 'Nombre d''unités', 'xml', 'tif:NbUnites', NULL, NULL, NULL, NULL, '', 'nbunites', 'N'),
(326, 156, 'Surface', 'xml', 'tif:SurfaceMoyenne[attribute::tif:unite="01.03.04.01"]', NULL, NULL, NULL, NULL, '', 'surface', 'N'),
(327, 156, 'Nom', 'xml', 'tif:Nom[attribute::xml:lang="fr"]', NULL, NULL, NULL, NULL, '', 'nom', 'N'),
(328, 156, 'Nombre de personnes (min)', 'xml', 'tif:Dispositions/tif:DetailDisposition[attribute::type="14.03.03.05"]/tif:CapaciteMini', NULL, NULL, NULL, NULL, '', 'personnesmin', 'N'),
(329, 156, 'Nombre de personnes (max)', 'xml', 'tif:Dispositions/tif:DetailDisposition[attribute::type="14.03.03.05"]/tif:CapaciteMaxi', NULL, NULL, NULL, NULL, '', 'personnesmax', 'N'),
(333, 107, 'Description FR', 'xml', 'tif:DescriptionTarif[attribute::xml:lang="fr"]', NULL, NULL, NULL, NULL, '', 'description_fr', 'N'),
(334, 107, 'Description EN', 'xml', 'tif:DescriptionTarif[attribute::xml:lang="en"]', NULL, NULL, NULL, NULL, '', 'description_en', 'N'),
(335, 107, 'Description ES', 'xml', 'tif:DescriptionTarif[attribute::xml:lang="es"]', NULL, NULL, NULL, NULL, '', 'description_es', 'N'),
(336, 107, 'Description DE', 'xml', 'tif:DescriptionTarif[attribute::xml:lang="de\n"]', NULL, NULL, NULL, NULL, '', 'description_de', 'N'),
(337, 107, 'Description NL', 'xml', 'tif:DescriptionTarif[attribute::xml:lang="nl"]', NULL, NULL, NULL, NULL, '', 'description_nl', 'N'),
(338, 107, 'Description IT', 'xml', 'tif:DescriptionTarif[attribute::xml:lang="it"]', NULL, NULL, NULL, NULL, '', 'description_it', 'N'),
(339, NULL, 'Capacités Globales - Nombre de personnes (hébergement)', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.03"][1]/tif:Capacite[attribute::unite="01.03.01.09" and attribute::classee="O"][1]', NULL, NULL, NULL, 'HLO,VIL', '', 'capacite_personne', 'N'),
(341, NULL, 'Classements - Patrimoine', 'xml', 'tif:Classements/tif:DetailClassement[contains(attribute::type, "06.04.02")]', NULL, NULL, NULL, 'PCU,PNA', '', 'patrimoine', 'N'),
(342, 341, 'Clé', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_TypeClassement', 'cle', 'Y'),
(343, NULL, 'Classements - Label HLO (Gîtes de France)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.03.02.01"][1]/tif:Classement/@type', NULL, NULL, NULL, 'HLO,VIL', 'LS_Classement', 'gites_de_france', 'N'),
(344, NULL, 'Capacités Unités - Couverts en salle', 'xml', 'tif:Capacites/tif:CapacitesUnites/tif:DetailCapaciteUnite[attribute::type="116.14.03.02.01"]/tif:NbUnites', NULL, NULL, NULL, 'RES', '', 'couverts_salle', 'N'),
(348, NULL, 'Capacités Globales - Nombre total de personnes (hébergement)', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.03"][2]/tif:Capacite[attribute::unite="01.03.01.09" and attribute::classee="O"]', NULL, NULL, NULL, 'HLO', '', 'capacite_globale', 'N'),
(349, NULL, 'Contact Etablissement - Téléphone / fax', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse[1]/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.06"]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG', '', 'telephone_fax', 'N'),
(350, NULL, 'Capacités Globales - Nombre total de chambres', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.02"][2]/tif:Capacite[attribute::unite="01.03.01.03" and attribute::classee="O"][1]', NULL, NULL, NULL, 'HOT,HLO', '', 'capacite_total_chambres', 'N'),
(351, NULL, 'Classements - Label HLO (Referentiel chambre d''hotes)', 'xml', 'tif:Classements/tif:DetailClassement[attribute::type="06.06.02.56"]/@type', NULL, NULL, NULL, 'HLO', '', 'referentiel_chhotes', 'N'),
(352, NULL, 'Périodes - Périodes d''ouverture (FMA)', 'xml', 'tif:Periodes/tif:DetailPeriode[attribute::type="09.01.05"]', NULL, NULL, NULL, 'FMA', '', 'ouverture_fma', 'N'),
(353, 352, 'Date de début', 'xml', 'tif:Dates/tif:DetailDates/tif:DateDebut', NULL, NULL, NULL, NULL, '', 'datedebut', 'N'),
(354, 352, 'Date de fin', 'xml', 'tif:Dates/tif:DetailDates/tif:DateFin', NULL, NULL, NULL, NULL, '', 'datefin', 'N'),
(355, 352, 'Description', 'xml', 'tif:ObservationDetailPeriode[attribute::xml:lang="fr"]', NULL, NULL, NULL, NULL, '', 'description', 'N'),
(356, 352, 'Type de période', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Periode', 'type', 'Y'),
(357, NULL, 'Périodes - Heure de Début FMA', 'xml', 'tif:Periodes/tif:DetailPeriode[attribute::type="09.01.05"]/tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.08"]/tif:Horaires/tif:HoraireDebut', NULL, NULL, NULL, 'FMA', '', 'heure_debut_manif', 'N'),
(358, NULL, 'Périodes - Heure de Fin FMA', 'xml', 'tif:Periodes/tif:DetailPeriode[attribute::type="09.01.05"]/tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.08"]/tif:Horaires/tif:HoraireFin', NULL, NULL, NULL, 'FMA', '', 'heure_fin_manif', 'N'),
(367, NULL, 'Périodes - Horaires d''ouverture RES', 'xml', 'tif:Periodes/tif:DetailPeriode[attribute::type="09.01.01"]/tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.08"]/tif:Horaires', NULL, NULL, NULL, 'HOT,HPA,HLO,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'horaires_RES', 'N'),
(368, 367, 'Heure de début', 'xml', 'tif:HoraireDebut', NULL, NULL, NULL, NULL, '', 'heure_debut', 'N'),
(369, 367, 'Heure de fin', 'xml', 'tif:HoraireFin', NULL, NULL, NULL, NULL, '', 'heure_fin', 'N'),
(370, NULL, 'Prestations liées', 'xml', 'tif:PrestationsLiees', NULL, NULL, NULL, 'ITI,PRD', '', 'prestations_liees', 'N'),
(386, NULL, 'Périodes - Périodes d''ouverture (avec horaires)', 'xml', 'tif:Periodes/tif:DetailPeriode', NULL, NULL, NULL, 'FMA,PCU', '', 'periode_ouverture', 'N'),
(387, 386, 'Date de début', 'xml', 'tif:Dates/tif:DetailDates/tif:DateDebut', NULL, NULL, NULL, NULL, '', 'datedebut', 'N'),
(388, 386, 'Date de fin', 'xml', 'tif:Dates/tif:DetailDates/tif:DateFin', NULL, NULL, NULL, NULL, '', 'datefin', 'N'),
(389, 386, 'Description', 'xml', 'tif:ObservationDetailPeriode[attribute::xml:lang="fr"]', NULL, NULL, NULL, NULL, '', 'description', 'N'),
(390, 386, 'Type de période', 'xml', '@type', NULL, NULL, NULL, NULL, 'LS_Periode', 'type', 'Y'),
(391, 386, 'Heure de début - Lundi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.02"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_lundi1', 'N'),
(392, 386, 'Heure de fin - Lundi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.02"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_lundi1', 'N'),
(393, 386, 'Heure de début - Lundi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.02"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_lundi2', 'N'),
(394, 386, 'Heure de fin - Lundi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.02"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_lundi2', 'N'),
(395, 386, 'Heure de début - Mardi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.03"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_mardi1', 'N'),
(396, 386, 'Heure de fin - Mardi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.03"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_mardi1', 'N'),
(397, 386, 'Heure de début - Mardi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.03"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_mardi2', 'N'),
(398, 386, 'Heure de fin - Mardi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.03"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_mardi2', 'N'),
(399, 386, 'Heure de début - Mercredi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.04"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_mercredi1', 'N'),
(400, 386, 'Heure de fin - Mercredi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.04"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_mercredi1', 'N'),
(401, 386, 'Heure de début - Mercredi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.04"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_mercredi2', 'N'),
(402, 386, 'Heure de fin - Mercredi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.04"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_mercredi2', 'N'),
(403, 386, 'Heure de début - Jeudi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.05"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_jeudi1', 'N'),
(404, 386, 'Heure de fin - Jeudi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.05"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_jeudi1', 'N'),
(405, 386, 'Heure de début - Jeudi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.05"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_jeudi2', 'N'),
(406, 386, 'Heure de fin - Jeudi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.05"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_jeudi2', 'N'),
(407, 386, 'Heure de début - Vendredi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.06"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_vendredi1', 'N'),
(408, 386, 'Heure de fin - Vendredi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.06"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_vendredi1', 'N'),
(409, 386, 'Heure de début - Vendredi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.06"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_vendredi2', 'N'),
(410, 386, 'Heure de fin - Vendredi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.06"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_vendredi2', 'N'),
(411, 386, 'Heure de début - Samedi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.07"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_samedi1', 'N'),
(412, 386, 'Heure de fin - Samedi 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.07"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_samedi1', 'N'),
(413, 386, 'Heure de début - Samedi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.07"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_samedi2', 'N'),
(414, 386, 'Heure de fin - Samedi 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.07"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_samedi2', 'N'),
(415, 386, 'Heure de début - Dimanche 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.01"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_dimanche1', 'N'),
(416, 386, 'Heure de fin - Dimanche 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.01"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_dimanche1', 'N');
INSERT INTO `sitChamp` (`idChamp`, `idChampParent`, `libelle`, `stockage`, `xpath`, `scope`, `versioning`, `plugin`, `bordereau`, `liste`, `identifiant`, `cle`) VALUES
(417, 386, 'Heure de début - Dimanche 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.01"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, NULL, 'heuredebut_dimanche2', 'N'),
(418, 386, 'Heure de fin - Dimanche 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.01"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, NULL, 'heurefin_dimanche2', 'N'),
(419, 386, 'Heure de début - Tous les jours 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.08"]/tif:Horaires[1]/tif:HoraireDebut', NULL, NULL, NULL, NULL, '', 'heuredebut_all1', 'N'),
(420, 386, 'Heure de fin - Tous les jours 1', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.08"]/tif:Horaires[1]/tif:HoraireFin', NULL, NULL, NULL, NULL, '', 'heurefin_all1', 'N'),
(421, 386, 'Heure de début - Tous les jours 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.08"]/tif:Horaires[2]/tif:HoraireDebut', NULL, NULL, NULL, NULL, '', 'heuredebut_all2', 'N'),
(422, 386, 'Heure de fin - Tous les jours 2', 'xml', 'tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.02"]/tif:Jour[attribute::lib_jour="09.02.08"]/tif:Horaires[2]/tif:HoraireFin', NULL, NULL, NULL, NULL, '', 'heurefin_all2', 'N'),
(423, NULL, 'Périodes - Jour de fermeture', 'xml', 'tif:Periodes/tif:DetailPeriode[attribute::type="09.01.01"]/tif:Dates/tif:DetailDates/tif:Jours/tif:DetailJours[attribute::type="09.03.01"]/tif:Jour/@lib_jour', NULL, NULL, NULL, 'HOT,HPA,HLO,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'jour_fermeture', 'N'),
(425, NULL, 'Contact Etablissement - Téléphone 3', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][3]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG,PRD', '', 'telephone3', 'N'),
(427, NULL, 'Contact Etablissement - Bureau distributeur', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse/tif:BureauDistrib', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'bureau_distributeur', 'N'),
(428, NULL, 'Contact Etablissement - Province/Etat', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.13"][1]/tif:Adresses/tif:DetailAdresse/tif:ProvinceEtat', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'province_etat', 'N'),
(429, NULL, 'Capacités Globales - Nombre max de personnes (hébergement)', 'xml', 'tif:Capacites/tif:CapacitesGlobales[attribute::type="14.01.03"][1]/tif:Capacite[attribute::unite="01.03.01.09" and attribute::classee="O"][2]', NULL, NULL, NULL, 'HLO', '', 'capacite_maximum', 'N'),
(430, 258, 'Inclus', 'xml', 'tif:PrestationsPlanning/tif:DetailPrestationPlanning/tif:DetailPrestation/tif:Inclus', NULL, NULL, NULL, NULL, '', 'inclus', 'N'),
(431, 258, 'Produit', 'xml', 'tif:PrestationsPlanning/tif:DetailPrestationPlanning/tif:DetailPrestation/tif:Prestation/@type', NULL, NULL, NULL, NULL, 'LS_Prestation', 'type_produit', 'N'),
(437, NULL, 'Informations complémentaires', 'xml', 'tif:DescriptionsComplementaires/tif:DetailDescriptionComplementaire[attribute::type="16.01.04"]/tif:Description[attribute::type="16.02.09"]', NULL, NULL, NULL, 'HLO', '', 'info_complementaire', 'N'),
(438, NULL, 'Prestations - Accessibilités', 'xml', 'tif:OffresPrestations/tif:DetailOffrePrestation[attribute::type="15.01"]/tif:DetailPrestation', NULL, NULL, NULL, 'HOT,HPA,HLO,PCU,PNA,RES,DEG,LOI,ASC,VIL', 'LS_Prestation', 'accessibilite', 'N'),
(439, 438, 'Accessibilité', 'xml', 'tif:Prestation/@type', NULL, NULL, NULL, NULL, 'LS_Prestation', 'cle', 'Y'),
(441, NULL, 'Clientèles', 'xml', 'tif:Clienteles/tif:DetailClienteles/@type', NULL, NULL, NULL, 'RES', '', 'clienteles', 'N'),
(442, 201, 'Copyright', 'xml', 'tif:Copyright', NULL, NULL, NULL, NULL, '', 'copyright_fichier', 'N'),
(454, 105, 'Distance', 'xml', 'tif:Distance', NULL, NULL, NULL, NULL, '', 'distance', 'N'),
(455, 105, 'Unite', 'xml', 'tif:Distance/@unite', NULL, NULL, NULL, NULL, 'LS_Unite', 'unite', 'N'),
(456, 104, 'Distance', 'xml', 'tif:Distance', NULL, NULL, NULL, NULL, '', 'distance', 'N'),
(457, 104, 'Unite', 'xml', 'tif:Distance/@unite', NULL, NULL, NULL, NULL, 'LS_Unite', 'unite', 'N'),
(458, 106, 'Distance', 'xml', 'tif:Distance', NULL, NULL, NULL, NULL, '', 'distance', 'N'),
(459, 106, 'Unite', 'xml', 'tif:Distance/@unite', NULL, NULL, NULL, NULL, 'LS_Unite', 'unite', 'N'),
(461, 201, 'Description', 'xml', 'tif:ObservationMultimedia', NULL, NULL, NULL, NULL, '', 'description_fichier', 'N'),
(466, NULL, 'Capacités Prestations', 'xml', 'tif:Capacites/tif:CapacitesPrestations/tif:DetailCapacitePrestation', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,ITI,VIL,ORG,PRD', '', 'capacite_prestations', 'N'),
(467, 466, 'Type', 'xml', '@type', NULL, NULL, NULL, NULL, '', 'type', 'Y'),
(468, 466, 'Capacité (min)', 'xml', 'tif:Capacite[1]', NULL, NULL, NULL, NULL, '', 'capacite_min', 'N'),
(469, 466, 'Capacité (max)', 'xml', 'tif:Capacite[2]', NULL, NULL, NULL, NULL, '', 'capacite_max', 'N'),
(470, 466, 'Descriptif', 'xml', 'tif:DescriptionCapacitePrestation', NULL, NULL, NULL, NULL, '', 'descriptif', 'N'),
(471, 201, 'Legende', 'xml', 'tif:LegendeRessource\n', NULL, NULL, NULL, NULL, '', 'legende_ressource', 'N'),
(472, NULL, 'Contact Propriétaire - Raison sociale', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:RaisonSociale', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_raison_sociale', 'N'),
(473, NULL, 'Contact Propriétaire - Prénom', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Prenom', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_prenom', 'N'),
(474, NULL, 'Contact Propriétaire - Nom', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Nom', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_nom', 'N'),
(475, NULL, 'Contact Propriétaire - Adresse 1', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Adr1', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_adresse1', 'N'),
(476, NULL, 'Contact Propriétaire - Adresse 2', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Adr2', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_adresse2', 'N'),
(477, NULL, 'Contact Propriétaire - Adresse 3', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Adr3', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_adresse3', 'N'),
(478, NULL, 'Contact Propriétaire - Code postal', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:CodePostal', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_code_postal', 'N'),
(479, NULL, 'Contact Propriétaire - Cedex', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Cedex', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_cedex', 'N'),
(480, NULL, 'Contact Propriétaire - Code Insee', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Commune/@code', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_code_insee', 'N'),
(481, NULL, 'Contact Propriétaire - Pays', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Pays/@code', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', 'LS_Pays', 'proprietaire_pays', 'N'),
(482, NULL, 'Contact Propriétaire - Téléphone 1', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][1]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_telephone1', 'N'),
(483, NULL, 'Contact Propriétaire - Téléphone 2', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][2]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_telephone2', 'N'),
(484, NULL, 'Contact Propriétaire - Fax', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.02"]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_fax', 'N'),
(485, NULL, 'Contact Propriétaire - Site web', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.05"][1]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_site_web', 'N'),
(486, NULL, 'Contact Propriétaire - Email', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.04"]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_email', 'N'),
(487, NULL, 'Contact Propriétaire - Commune', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.30"][1]/tif:Adresses/tif:DetailAdresse/tif:Commune', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'proprietaire_commune', 'N'),
(488, NULL, 'Contact Réservation - Raison sociale', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:RaisonSociale', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_raison_sociale', 'N'),
(489, NULL, 'Contact Réservation - Prénom', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Prenom', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_prenom', 'N'),
(490, NULL, 'Contact Réservation - Nom', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:Nom', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_nom', 'N'),
(491, NULL, 'Contact Réservation - Adresse 1', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Adr1', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_adresse1', 'N'),
(492, NULL, 'Contact Réservation - Adresse 2', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Adr2', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_adresse2', 'N'),
(493, NULL, 'Contact Réservation - Adresse 3', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Adr3', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_adresse3', 'N'),
(494, NULL, 'Contact Réservation - Code postal', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:CodePostal', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_code_postal', 'N'),
(495, NULL, 'Contact Réservation - Cedex', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Cedex', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_cedex', 'N'),
(496, NULL, 'Contact Réservation - Code Insee', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Commune/@code', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_code_insee', 'N'),
(497, NULL, 'Contact Réservation - Pays', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Pays/@code', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', 'LS_Pays', 'reservation_pays', 'N'),
(498, NULL, 'Contact Réservation - Téléphone 1', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][1]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_telephone1', 'N'),
(499, NULL, 'Contact Réservation - Téléphone 2', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.01"][2]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_telephone2', 'N'),
(500, NULL, 'Contact Réservation - Fax', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.02"]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_fax', 'N'),
(501, NULL, 'Contact Réservation - Site web', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.05"][1]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_site_web', 'N'),
(502, NULL, 'Contact Réservation - Email', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Personnes/tif:DetailPersonne[attribute::type="04.04.05"]/tif:MoyensCommunications/tif:DetailMoyenCom[attribute::type="04.02.04"]/tif:Coord', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_email', 'N'),
(503, NULL, 'Contact Réservation - Commune', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.33"][1]/tif:Adresses/tif:DetailAdresse/tif:Commune', NULL, NULL, NULL, 'HOT,HPA,HLO,FMA,PCU,PNA,RES,DEG,LOI,ASC,VIL,ORG', '', 'reservation_commune', 'N'),
(512, 107, 'Observation Periode', 'xml', 'tif:DetailPeriode[attribute::type="09.01.08"]/tif:Dates/tif:DetailDates/tif:ObservationDates[attribute::xml:lang="fr"]', NULL, NULL, NULL, NULL, '', 'observation_periode', 'N'),
(513, NULL, 'Contact Etablissement - Nom de l''établissement', 'xml', '/tif:OI/tif:Contacts/tif:DetailContact[attribute::type="04.03.14"]/tif:RaisonSociale', NULL, NULL, NULL, 'FMA', '', 'nom_etablissement', 'N');
