/**
 * @version		0.4 alpha-test - 2013-06-03
 * @package		Tourism System Client
 * @copyright	Copyright (C) 2010 Raccourci Interactive
 * @license		GNU GPLv3 ; see LICENSE.txt
 * @author		Jeremie Perrin <jeremie.raccourci@gmail.com>
 */

Ext.ts.Lang = {
	titleAppli: 'Tourism System v2',

	// MENU
	menuFiches: 'Fiches',
	menuUtilisateurs: 'Utilisateurs',
	menuProfils: 'Profils',
	menuGroupes: 'Groupes',
	menuTerritoires: 'Territoires',
	menuChamps: 'Champs',
	menuThesaurii: 'Thesaurii',
	menuPlugins: 'Plugins',
	menuHelp: 'Aide',
	menuDeconnexion: 'Déconnexion',

	// EXT USER
	waitTitle: 'Veuillez patienter',
	waitMsg: 'Chargement en cours',
	confirmTitle: 'Confirmation',
	failureTitle: 'Echec',
	failureMsg: "Une erreur s'est produite durant l'opération.",
	timeoutMsg: "Délai d'attente expiré. Veuillez réessayer ultérieurement.",
	expiredMsg: "Votre session est expirée",
	authMsg: "Veuillez vous authentifier",
	switchUser: "Changer d'utilisateur",
	gridEmptyText: 'Aucune donnée à afficher',
	autocompleteEmptyText: 'Aucune donnée trouvée',
	autocompleteFiches: 'Rechercher une fiche...',
	rechercheCommuneEmpty: 'Aucune commune trouvée',
	autosizepagingSizeField: 'Ligne/page : ',
	fileuploadfieldEmptyText: 'Choisissez un fichier...',
	helpTitle: 'Aide Tourism System',
	helpEmpty: 'Sélectionnez la page qui vous intéresse...',

	// SEARCH ENGINE
	codeInsee: 'Code INSEE',
	codePostal: 'Code postal',
	filterByCommune: 'Trier par commune',
	rechercheCommune: 'Rechercher une commune',
	chooseBordereau: 'Choisir un bordereau',
	filterByBordereau: 'Trier par bordereau',
	commune: 'Commune',
	critereOr: 'Répondre à au moins un de ces critères',
	critereAnd: 'Répondre à tous ces critères',
	addCritere: 'Ajouter un critère',
	expandAll: 'Tout déplier',
	collapseAll: 'Tout replier',
	critere: 'Critère',
	autres: 'Autres',
	entrerValeur: 'Entrez la valeur',
	inferieur: 'inférieur à',
	inferieurEgal: 'inférieur ou égal à',
	egal: 'égal à',
	superieur: 'supérieur ou égal à',
	superieurEgal: 'supérieur à',
	operateur: 'Opérateur',
	valeur: 'Valeur',
	duLc: 'du',
	duUc: 'Du',
	auLc: 'au',
	auUc: 'Au',

	// AUTH
	moreInfoAt: "Plus d'informations sur",
	login: 'Identifiant',
	password: 'Mot de passe',
	seConnecter: 'Se connecter',
	forgottenPass: 'Mot de passe oublié',
	authWaitMsg: 'Identification en cours',
	authSuccess: "Identification réussie<br/>Chargement en cours...",
	retrievePass: 'Récupérer le mot de passe',
	sendPassWaitMsg: 'Envoi en cours',
	sendPassError: 'Veuillez saisir votre adresse mail',
	msgIE7: "Tourism System n'est pas optimisé pour Internet Explorer 7 et toutes les versions antérieurs.\nMerci d'utiliser un autre navigateur (Chrome, Firefox, Internet Explorer 8+).",

	// DIVERS
	francais: 'Français',
	anglais: 'Anglais',
	allemand: 'Allemand',
	espagnol: 'Espagnol',
	neerlandais: 'Néerlandais',
	italien: 'Italien',
	root: 'Root',
	bordereau: 'Bordereau',
	bordereaux: 'Bordereaux',
	ouvrir: 'Ouvrir',
	dupliquer: 'Dupliquer',
	valider: 'Valider',
	annuler: 'Annuler',
	precedent: 'Précedent',
	suivant: 'Suivant',
	accueil: 'Accueil',
	outils: 'Outils',
	actions: 'Actions',
	ajouter: 'Ajouter',
	modifier: 'Modifier',
	supprimer: 'Supprimer',
	desassocier: 'Désassocier',
	fermer: 'Fermer',
	recherche: 'Recherche',
	rechercher: 'Rechercher',
	enregistrer: 'Enregistrer',
	appliquer: 'Appliquer',
	visualiser: 'Visualiser',
	reinitialiser: 'Réinitialiser',
	sommaire: 'Sommaire',
	parcourir: 'Parcourir',
	envoyer: 'Envoyer',
	format: 'Format',
	fichier: 'Fichier',
	attention: 'Attention',
	deplacer: 'Déplacer',
	monter: 'Monter',
	descendre: 'Descendre',
	activer: 'Activer',
	desactiver: 'Désactiver',
	oui: 'Oui',
	non: 'Non'
};
